import { createRouter } from '@tanstack/react-router'
// routeTree is auto-generated by @tanstack/router-vite-plugin on `bun dev`
import { routeTree } from './routeTree.gen'

export const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
})

// Register router type for full type-safety across the app
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}
